### ISSUE TITLE
Establish process to create DOI

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#112]
There should be a process to create a citable DOI. Potentially a Github Action on a push to the main branch, which then publishes the release to Zenodo.

Investigate options and implement most suitable one.

**Comment by MarionBWeinzierl** [comment]
This seems to be a semi-automated way, with manually created releases: https://coderefinery.github.io/github-without-command-line/doi/

**Comment by MarionBWeinzierl** [comment]
There is this (archived/unmaintained) repository which would enable to integration with Github Actions: https://github.com/actions/create-release

**Comment by MarionBWeinzierl** [comment]
@davidorme , would you prefer the fully automated way over the actions, or the semi-automated way which still requires you to manually create a release in Github?

**Comment by davidorme** [comment]
I think the semi-automated way. I've just created a release for the last tag published to PyPI but hadn't really thought through all the steps! https://zenodo.org/record/8366848

1. What metadata gets passed - the authorship and description could do with some work! Fortunately, the metadata and descriptions can be edited both on Github and Zenodo - it is only the code that is fixed by the tag and by the uploaded Zenodo zipball.
2. The format of the release notes. I think @mondus mentioned something about turning the existing Changes document into something more formal.
3. Attached files. I'm not inclined to add the binaries to the release - those are on PyPI and so we can link there and have a single canonical source. People shouldn't be installing the package from Zenodo, it is just a DOI for the tag.

**Comment by MarionBWeinzierl** [comment]
OK, sorry, I am a bit confused now. Do you still want me to do something with this (clean up the meta data or so), or have you already done it?

**Comment by davidorme** [comment]
Yeah I jumped the gun on this one - I think I need a template for what information should be included here and that needs a bit more thought, so let's leave this one for now.
